make-pair: exits if check fails for $KEY_ORG

diff --git a/make-pair b/make-pair
--- a/make-pair
+++ b/make-pair
@@ -167,7 +167,8 @@ shift       # get rid of the "--"
 
 # == sanity checking ==
 if [ -z "$KEY_ORG" ] ; then
-  echo "$self: FATAL ERROR: \$KEY_ORG not defined.  Edit and source 'vars'." >&2
+  echo "$self: FATAL ERROR: \$KEY_ORG not set.  Edit and source 'vars'." >&2
+  exit 5
 fi
 
 
